### ISSUE TITLE
Skipping bytes & Changing position

### ISSUE THREAD

**Issue by faustbrian** [Bit-Wasp/buffertools-php#73]
Is there currently a way to skip a byte and manually move the position forward and backward? I looked for any skip, rewind or any methods that would allow me to modify the `position` variable but there doesn't seem to be one.

```php
<?php

(new TemplateFactory())
    ->uint64le()
    ->uint8le() // Reading a byte to skip it
    ->uint64le()
    ->getTemplate()
    ->parse($parser);
```

This is what I am currently doing to skip a byte but that seems rather weird. Is there any better way skip N bytes?

**Comment by afk11** [comment]
Easiest way, though only in the forward direction, use bytestring and pass the number of bytes?

**Comment by faustbrian** [comment]
That is the solution I came up with after opening this issue for skipping bytes. Would guess there is currently no way to move the cursor backwards?
