### ISSUE TITLE
release PHP 7.4 compatible version

### ISSUE THREAD

**Issue by ItsANameToo** [Bit-Wasp/buffertools-php#97]
Can you tag a new release now that https://github.com/Bit-Wasp/buffertools-php/pull/91 is merged? This fixes an issue when using PHP 7.4 as it will otherwise error on the deprecated use of the ternary operator.

Right now using https://github.com/Bit-Wasp/bitcoin-php does not pull in this fix as it's not in one of the releases.

**Comment by afk11** [comment]
Hi, thanks for reminding me. I'll try get to this on the weekend.

**Comment by ItsANameToo** [comment]
👀

**Comment by afk11** [comment]
Tagged as v0.5.7 :)

**Comment by ItsANameToo** [comment]
awesome, thank you!
